// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocol/chatbot.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TEXT   MessageType = 0
	MessageType_SYSTEM MessageType = 1 // Join/Leave
)

var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":   0,
		"SYSTEM": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_chatbot_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_protocol_chatbot_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_chatbot_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderName    string                 `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=chatbot.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protocol_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Message) Descriptor() ([]byte, []int) {
	return file_protocol_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protocol_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Response) Descriptor() ([]byte, []int) {
	return file_protocol_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Response) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

var File_protocol_chatbot_proto protoreflect.FileDescriptor

const file_protocol_chatbot_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/chatbot.proto\x12\achatbot\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\aMessage\x12\x1f\n" +
	"\vsender_name\x18\x01 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.chatbot.MessageTypeR\x04type\"\x86\x01\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt*#\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x012t\n" +
	"\x0eChatbotService\x122\n" +
	"\vSendMessage\x12\x10.chatbot.Message\x1a\x11.chatbot.Response\x12.\n" +
	"\x04Chat\x12\x10.chatbot.Message\x1a\x10.chatbot.Message(\x010\x01B/Z-github.com/rainadwivedi/grpc-chatbot/protocolb\x06proto3"

var (
	file_protocol_chatbot_proto_rawDescOnce sync.Once
	file_protocol_chatbot_proto_rawDescData []byte
)

func file_protocol_chatbot_proto_rawDescGZIP() []byte {
	file_protocol_chatbot_proto_rawDescOnce.Do(func() {
		file_protocol_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_chatbot_proto_rawDesc), len(file_protocol_chatbot_proto_rawDesc)))
	})
	return file_protocol_chatbot_proto_rawDescData
}

var file_protocol_chatbot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_chatbot_proto_goTypes = []any{
	(MessageType)(0),              // 0: chatbot.MessageType
	(*Message)(nil),               // 1: chatbot.Message
	(*Response)(nil),              // 2: chatbot.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_protocol_chatbot_proto_depIdxs = []int32{
	3, // 0: chatbot.Message.sent_at:type_name -> google.protobuf.Timestamp
	0, // 1: chatbot.Message.type:type_name -> chatbot.MessageType
	3, // 2: chatbot.Response.received_at:type_name -> google.protobuf.Timestamp
	1, // 3: chatbot.ChatbotService.SendMessage:input_type -> chatbot.Message
	1, // 4: chatbot.ChatbotService.Chat:input_type -> chatbot.Message
	2, // 5: chatbot.ChatbotService.SendMessage:output_type -> chatbot.Response
	1, // 6: chatbot.ChatbotService.Chat:output_type -> chatbot.Message
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protocol_chatbot_proto_init() }
func file_protocol_chatbot_proto_init() {
	if File_protocol_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_chatbot_proto_rawDesc), len(file_protocol_chatbot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_chatbot_proto_goTypes,
		DependencyIndexes: file_protocol_chatbot_proto_depIdxs,
		EnumInfos:         file_protocol_chatbot_proto_enumTypes,
		MessageInfos:      file_protocol_chatbot_proto_msgTypes,
	}.Build()
	File_protocol_chatbot_proto = out.File
	file_protocol_chatbot_proto_goTypes = nil
	file_protocol_chatbot_proto_depIdxs = nil
}
