// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: protocol/chatbot.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ChatbotService_SendMessage_FullMethodName = "/chatbot.ChatbotService/SendMessage"
	ChatbotService_Chat_FullMethodName        = "/chatbot.ChatbotService/Chat"
)

// ChatbotServiceClient is the client API for ChatbotService service.
type ChatbotServiceClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type chatbotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotServiceClient(cc grpc.ClientConnInterface) ChatbotServiceClient {
	return &chatbotServiceClient{cc}
}

func (c *chatbotServiceClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ChatbotService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatbotService_ServiceDesc.Streams[0], ChatbotService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

type ChatbotService_ChatClient = grpc.BidiStreamingClient[Message, Message]

// ChatbotServiceServer is the server API for ChatbotService service.
// All implementations must embed UnimplementedChatbotServiceServer.
type ChatbotServiceServer interface {
	SendMessage(context.Context, *Message) (*Response, error)
	Chat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedChatbotServiceServer()
}

type UnimplementedChatbotServiceServer struct{}

func (UnimplementedChatbotServiceServer) SendMessage(context.Context, *Message) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatbotServiceServer) Chat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatbotServiceServer) mustEmbedUnimplementedChatbotServiceServer() {}
func (UnimplementedChatbotServiceServer) testEmbeddedByValue()                        {}

type UnsafeChatbotServiceServer interface {
	mustEmbedUnimplementedChatbotServiceServer()
}

func RegisterChatbotServiceServer(s grpc.ServiceRegistrar, srv ChatbotServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatbotService_ServiceDesc, srv)
}

func _ChatbotService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatbotServiceServer).Chat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

type ChatbotService_ChatServer = grpc.BidiStreamingServer[Message, Message]

// ChatbotService_ServiceDesc is the grpc.ServiceDesc for ChatbotService service.
var ChatbotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatbot.ChatbotService",
	HandlerType: (*ChatbotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChatbotService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChatbotService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protocol/chatbot.proto",
}
